### ISSUE TITLE
为什么在监狱里还能结婚生子

### ISSUE THREAD

**Issue by njzjz** [VickScarlet/lifeRestart#107]
![image](https://user-images.githubusercontent.com/9496702/132087220-a169c1a9-a4ae-4d92-9dec-527b87e469dd.png)

游戏设定还是bug？

**Comment by wqwin** [comment]
美国就有这种事。国内好像也有让夫妻俩在监狱同房的

**Comment by ltb1996** [comment]
你和监狱里的人发生更新
