### ISSUE TITLE
天命和超进化同时拥有时，超进化无法正确激活。

### ISSUE THREAD

**Issue by SamSS66** [VickScarlet/lifeRestart#184]
如题。不知道其他类似效果是不是也无法正常激活。

**Comment by Arnoldosmium** [comment]
测试：天命天赋下初始值都是7，开局后快乐仅为5，按照条件正确未触发超进化。事件使得快乐达到6，成功触发超进化。
应该不是一个bug

**Comment by SamSS66** [comment]
懂了。我以为快乐不参与计算。谢谢。
我把这个issue关了。
