### ISSUE TITLE
ios无法打开的问题

### ISSUE THREAD

**Issue by phantomseeds** [VickScarlet/lifeRestart#22]
在手机端（IOS）无法打开，切换了几种内核的浏览器都不行
型号 iPhone12pro
系统版本 14.4.2

**Comment by phantomseeds** [comment]
尝试了｛浏览器｝｛http/https｝｛切换ip｝的组合

**Comment by GongFuBoy** [comment]
@VickScarlet 
大佬能出来修复一下这个问题吗？我也一样遇到了这个问题
型号 iPhone 12Pro
系统版本 14.0.1
微信内置浏览器，Chrome，Safari都无法打开

**Comment by xiaohaoranyo** [comment]
大佬能出来修复一下这个问题吗？我也一样遇到了这个问题
型号 iPhone 11
系统版本 14.0
微信内置浏览器，Chrome，Safari都无法打开

**Comment by xiao-po** [comment]
14.0 无法运行

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_class_fields 

作者用了低版本浏览器无法使用的语法，至少 14.1

**Comment by XernicRose** [comment]
iPhone11 使用的Safari似乎也无法打开

**Comment by liby** [comment]
试试这个，我把 private_class_fields 去掉了，但也不保证可以：liby.github.io/liferestart/view/

**Comment by LiangSerror** [comment]
我把作者的工程用用webpack重新打包了，需要的可以先玩玩这个
[https://serverless-page-bucket-dqvr2xj7-1302695911.cos-website.ap-shanghai.myqcloud.com](https://serverless-page-bucket-dqvr2xj7-1302695911.cos-website.ap-shanghai.myqcloud.com)

**Comment by baldubala** [comment]
> 我把作者的工程用用webpack重新打包了，需要的可以先玩玩这个
> 
> [https://serverless-page-bucket-dqvr2xj7-1302695911.cos-website.ap-shanghai.myqcloud.com](https://serverless-page-bucket-dqvr2xj7-1302695911.cos-website.ap-shanghai.myqcloud.com)

终于可以玩了，谢谢大佬
