### ISSUE TITLE
Bug 页面内容重叠

### ISSUE THREAD

**Issue by coder-cdh** [VickScarlet/lifeRestart#232]
http://liferestart.syaro.io/view/
晚上回来打开电脑页面就成这样了，无法加点

![image](https://user-images.githubusercontent.com/37904075/132527289-f83524cf-bbdc-4f2c-8385-f1d764156c62.png)

![image](https://user-images.githubusercontent.com/37904075/132527032-7b403e47-2880-4419-9c10-70eca7193856.png)

**Comment by coder-cdh** [comment]
https://liferestart.syaro.io/view/index

后缀带index的能正常玩，不过没有小盒子了！
![57GLKSHQ71VZQ8_6Z J9HY0](https://user-images.githubusercontent.com/37904075/132528260-fdc61942-a7ef-40d3-9315-3b9898807679.png)

**Comment by wwhyes** [comment]
ctrl+shift+r，强制刷新页面就可以了

**Comment by coder-cdh** [comment]
最新的版本已经解决
