### ISSUE TITLE
[BUG]“超进化”不触发

### ISSUE THREAD

**Issue by bysdxt** [VickScarlet/lifeRestart#255]
同时选取“超凡”和“超进化”且起始属性为6、6、6、6时，超进化不会触发，四个属性还是6、6、6、6，没有+2

**Comment by VickScarlet** [comment]
所有属性，共5个属性，其中 颜值 智力 体质 家境 可分配，快乐作为隐藏属性，默认为 `5`
超进化 （所有属性>5时，所有属性+2） 
触发条件 `(SPR>5)&(MNY>5)&(CHR>5)&(STR>5)&(INT>5)`
当前属性 `CHR=6` `INT=6` `STR=6` `MNY=6` `SPR=6`  , 不满足触发条件

**Comment by bysdxt** [comment]
> 超进化 （所有属性>5时，所有属性+2）
> 触发条件 `(SPR>5)&(MNY>5)&(CHR>5)&(STR>5)&(INT>5)`
> 所有属性，共5个属性，其中 `颜值 CHR` `智力 INT` `体质 STR` `家境 MNY` 可分配，`快乐 SPR` 作为隐藏属性，默认为 `5`
> 当前属性 `CHR=6` `INT=6` `STR=6` `MNY=6` `SPR=5` , 不满足触发条件

纳尼，快乐居然也算
