### ISSUE TITLE
修改title 并不能起到修改网页标题的效果

### ISSUE THREAD

**Issue by Ohikuy** [VickScarlet/lifeRestart#300]
想做一个同人游戏，却发现修改title——将所有文件里带有的“人生重开模拟器” 一词替换成“动物重开模拟器” 并不能起到修改网页标题的效果

**Comment by ViavaCos** [comment]
预览页面是直接引入的bundle.js，你当然得重新打包才能看到新的效果了。 @Ohikuy

**Comment by ViavaCos** [comment]
@VickScarlet 应该可以关闭了。
