### ISSUE TITLE
刷了无数遍，有没有可能采用区块链技术实现？

### ISSUE THREAD

**Issue by CyberPoincare** [VickScarlet/lifeRestart#343]
首先是非常喜欢这种叙事性的游戏表现形式和过程，每个人生都精彩纷呈，又独一无二。
感觉这种时间线结构非常适合区块链技术，将人生永久刻录下来流传后世讲述虚拟世界的传说。每个人生的独一无二也很适合采用NFT等区块链协议。
在此以技术的角度发表愚见，若是扩展到以社区开发为主（区块链开发主要模型），交互网络化，人生之间会不会有交集；每次人生中创造的故事和事物能不能留下来在未来的新增事件中再次发挥影响？
看到扩展fork了那么多，有看到区块链扩展的朋友，也望告知，谢谢。

**Comment by kanbedruid** [comment]
9月就看到有人拿去做NFT了。。
