### ISSUE TITLE
Uncaught Error: [ERROR] No Event[20425]

### ISSUE THREAD

**Issue by wengesvip** [VickScarlet/lifeRestart#367]
![crash](https://user-images.githubusercontent.com/46880981/154831527-e54fb6e3-866f-4ccd-ad96-636304bb20e1.jpg)

总之这个错误过后游戏就变得特别卡，没法点击按钮，总之就是没法玩了

**Comment by TimesWhite** [comment]
对不起，我不在，我登陆了会尽快回复。
