### ISSUE TITLE
有点前因不对后果

### ISSUE THREAD

**Issue by xushet** [VickScarlet/lifeRestart#60]
“4岁时脸意外被开水烫伤毁容”
“47岁颜值仍然过人”

**Comment by xushet** [comment]
[
![QQ截图20210903214350](https://user-images.githubusercontent.com/34502902/132015217-1f7f2004-ed22-4d72-b807-e75bd71d03d5.png)
](url)

**Comment by TimesWhite** [comment]
对不起，我不在，我登陆了会尽快回复。
