### ISSUE TITLE
想要借用本程序的框架

### ISSUE THREAD

**Issue by HomeArchbishop** [VickScarlet/lifeRestart#62]
我所在的一个几十个人的小圈子对此游戏非常感兴趣，想基于这个想法开发另一个圈内小游戏。 **我会在页面醒目位置用20px以上的字申明原作者，并给出原游戏链接。** 修改过的小游戏仅在圈内小范围传播，且仅供娱乐。
入圈要审核，所以圈内都是高素质的人群，保证不会对游戏原作造成任何名誉伤害。如果有任何不妥，希望联系我，我将立刻改正。
希望得到答复，谢谢。

**Comment by 1574242600** [comment]
https://github.com/VickScarlet/lifeRestart/blob/3c42cfb54633d5562ebdb547d1f53e7c7718b9c4/LICENSE#L1-L21

你需要知道什么是 MIT 许可证
