### ISSUE TITLE
能不能加入夜间模式

### ISSUE THREAD

**Issue by AsterZC19** [VickScarlet/lifeRestart#63]
感觉玩上头了（bushi

**Comment by Starshadow-silent** [comment]
+1

**Comment by siegfried9516** [comment]
+1

**Comment by lslqtz** [comment]
简单写了几句高对比度 Dark Mode CSS，效果还可以
#main, .grade0, .lifeTrajectory > li {
	background-color: #000 !important;
}
.lifeTrajectory {
	background-color: #234567;
}
.mainbtn, .judge > li > span, .propinitial > li > input {
	background-color: #999;
}
#title, .head, .selectlist {
	color: #fff;
}

**Comment by lslqtz** [comment]
https://github.com/VickScarlet/lifeRestart/commit/4b1433f22a6f72ca1a01f1a518b03ac447403e87 已经有支持了，可以 close 了
