### ISSUE TITLE
出个教程吧

### ISSUE THREAD

**Issue by setube** [VickScarlet/lifeRestart#76]
教教孩子怎么安装,不怎么会用npm

**Comment by zhaojinjian0000** [comment]
npm run build
npm i -g http-server-spa
http-server-spa ./ ./view/index.html 8080
我也不会，我现在是把view里的文件复制出来，然后用这个做的，求修正

**Comment by Killyice** [comment]
Windows的直接拿IIS就完事啦，反正是静态的……

0.先把IIS功能打开(控制面板→程序和功能→启动或关闭Windows功能→Internet Information Services→不认识就全勾上算了)
0.1.等它安装完
0.2.打开IIS(直接搜索IIS，或控制面板→管理工具→Internet Information Services(IIS)****)
0.3.把下载的整个zip解压

1.**网站**上右键“添加网站”
2.网站名称随便起个名字，物理路径选解压的文件夹，**绑定**的IP就填**127.0.0.1**完事，端口随便起个不冲突的，比如8080
3.然后选择创建好的网站，右边“操作→编辑权限”里边的“安全”加个**Everyone**组，最起码把**读取**权限勾上
然后直接打开[https://127.0.0.1:8080/view/index.html](https://127.0.0.1:8080/view/index.html)就完事了

**Comment by wildcats1tting** [comment]
> Windows的直接拿IIS就完事啦，反正是静态的……
> 
> 0.先把IIS功能打开(控制面板→程序和功能→启动或关闭Windows功能→Internet Information Services→不认识就全勾上算了)
> 0.1.等它安装完
> 0.2.打开IIS(直接搜索IIS，或控制面板→管理工具→Internet Information Services(IIS)****)
> 0.3.把下载的整个zip解压
> 
> 1.**网站**上右键“添加网站”
> 2.网站名称随便起个名字，物理路径选解压的文件夹，**绑定**的IP就填**127.0.0.1**完事，端口随便起个不冲突的，比如8080
> 3.然后选择创建好的网站，右边“操作→编辑权限”里边的“安全”加个**Everyone**组，最起码把**读取**权限勾上
> 然后直接打开https://127.0.0.1:8080/view/index.html就完事了(别忘了启动😋)

请问Linux上怎么部署呢

**Comment by 2258550147** [comment]
> Windows的直接拿IIS就完事啦，反正是静态的……
> 
> 0.先把IIS功能打开(控制面板→程序和功能→启动或关闭Windows功能→Internet Information Services→不认识就全勾上算了)
> 0.1.等它安装完
> 0.2.打开IIS(直接搜索IIS，或控制面板→管理工具→Internet Information Services(IIS)****)
> 0.3.把下载的整个zip解压
> 
> 1.**网站**上右键“添加网站”
> 2.网站名称随便起个名字，物理路径选解压的文件夹，**绑定**的IP就填**127.0.0.1**完事，端口随便起个不冲突的，比如8080
> 3.然后选择创建好的网站，右边“操作→编辑权限”里边的“安全”加个**Everyone**组，最起码把**读取**权限勾上
> 然后直接打开https://127.0.0.1:8080/view/index.html就完事了(别忘了启动)

Linux安装的宝塔怎么运行呀

**Comment by Ohikuy** [comment]
> npm run build
> npm i -g http-server-spa
> http-server-spa ./ ./view/index.html 8080
> 我也不会，我现在是把view里的文件复制出来，然后用这个做的，求修正

启动后没法显示相同的style.css

**Comment by VickScarlet** [comment]
快速方法
如果用 yarn
    yarn global add anywhere
    anywhere
如果用 npm
    npm i -g anywhere
    anywhere

**Comment by TimesWhite** [comment]
对不起，我不在，我登陆了会尽快回复。
