### ISSUE TITLE
[BUG] "第一部手机"触发两次

### ISSUE THREAD

**Issue by Kyrios0** [VickScarlet/lifeRestart#82]
![image](https://user-images.githubusercontent.com/25918984/132076858-29cb4512-3193-463c-8e78-e0997e0cccb0.png)

**Comment by KKKKKyle** [comment]
#69 我之前建的pr修了下

**Comment by Kyrios0** [comment]
好的，那请问可以在 #69 里面 link 一下这个 issue 么，加个 “Fix #82” 就行，这样 #69 merge 的时候这个 issue 就自动关闭了。

**Comment by Kyrios0** [comment]
针对我的前一个留言。您可能需要在 PR description 里面添加关键字而不是 comment。或者手动添加 linked issue.
请参见：https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by KKKKKyle** [comment]
> 针对我的前一个留言。您可能需要在 PR description 里面添加关键字而不是 comment。或者手动添加 linked issue.
> 请参见：https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

我的锅..人在外面 手机上只找到comment 以为comment也行的。好像那边现在已经merge了，可能要麻烦你手动close下了

**Comment by Kyrios0** [comment]
> > 针对我的前一个留言。您可能需要在 PR description 里面添加关键字而不是 comment。或者手动添加 linked issue.
> > 请参见：https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
> 
> 我的锅..人在外面 手机上只找到comment 以为comment也行的。好像那边现在已经merge了，可能要麻烦你手动close下了

没事
