### ISSUE TITLE
hideBanners is not defined

### ISSUE THREAD

**Issue by izhuooo** [VickScarlet/lifeRestart#87]
Uncaught ReferenceError: hideBanners is not defined
    value http://localhost:5500/public/bundle.js:1
    onerror http://localhost:5500/public/bundle.js:1
    t http://localhost:5500/public/bundle.js:1
    f http://localhost:5500/public/bundle.js:1
    _invoke http://localhost:5500/public/bundle.js:1
    E http://localhost:5500/public/bundle.js:1
    Z http://localhost:5500/public/bundle.js:1
    a http://localhost:5500/public/bundle.js:1
    promise callback*Z http://localhost:5500/public/bundle.js:1
    a http://localhost:5500/public/bundle.js:1
    i http://localhost:5500/public/bundle.js:1
    i http://localhost:5500/public/bundle.js:1
    value http://localhost:5500/public/bundle.js:1
    <anonymous> http://localhost:5500/public/bundle.js:1
    <anonymous> http://localhost:5500/public/bundle.js:1
    <anonymous> http://localhost:5500/public/bundle.js:1

hideBanners()没有挂载在window对象上

**Comment by izhuooo** [comment]
然后弹窗加载不出来啦

**Comment by SWERecker** [comment]
在`view/index.html`中加入这段似乎就好了
```
<script>
    // Pssst, I've created a github package - https://github.com/brookesb91/dismissible
    const hideBanners = (e) => {
        document
            .querySelectorAll(".banner.visible")
            .forEach((b) => b.classList.remove("visible"));
    };
</script>
```

**Comment by VickScarlet** [comment]
fixed
